version: '3'

services:
  jekyll:
    image: jekyll/jekyll:pages
    container_name: ejball_com
    command: jekyll serve --force_polling --livereload --drafts --verbose
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./:/srv/jekyll
